dist: trusty
sudo: true
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

before_install:
  - sudo apt-get install xorg-dev libglu1-mesa-dev
  - pip install --user cpp-coveralls

script:
  - CXX=/usr/bin/g++-5 CC=/usr/bin/gcc-5 cmake . -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGRAPHICS_API:STRING=OPENGL -DCOVERAGE=1
  - cmake --build .
  - ./bin/seed-engine-core-tests

after_success:
  - coveralls --root . -E ".*extern." -E ".*build" -E ".*bin" -E ".*lib" -E ".*scripts" -E ".*ci" -E ".*cmake"