os:
  - linux
dist: trusty
sudo: require
language: cpp
compiler:
  - gcc
  - clang

install:
  # /usr/bin/gcc is 4.6 always, but gcc-X.Y is available.
  - if [[ $CXX = g++ ]]; then export CXX="g++-6" CC="gcc-6"; fi
  # /usr/bin/clang has a conflict with gcc, so use clang-X.Y.
  - if [[ $CXX = clang++ ]]; then export CXX="clang++-4.0" CC="clang-4.0"; fi

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - h-rayflood/llvm
      - llvm-toolchain-precise-4.0
    packages:
      - gcc-6
      - g++-6
      - clang-4.0
      - cmake

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update ;
      brew install qt5 cmake ;
      brew link --force qt ;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      # Link gcc-6 and g++-6 to their standard commands
      sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
      sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
      # Install GLFW dependency
      sudo apt-get install xorg-dev libglu1-mesa-dev
      # Install coveralls
      #pip install --user cpp-coveralls
    fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      # Export CC and CXX to tell cmake which compiler to use
      export CC=/usr/bin/gcc-6
      export CXX=/usr/bin/g++-6
      # Check versions of gcc, g++ and cmake
      gcc -v && g++ -v && cmake --version
      # Enable coveralls
      #- ./configure --enable-gcov
      cmake . -G "Unix Makefiles" -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGRAPHICS_API:STRING=OPENGL
    fi
  # Build
  - cmake --build .
  # Run tests
  - ./bin/seed-engine-core-tests

after_success:
  #- coveralls --root . -E ".*extern." -E ".*build" -E ".*bin" -E ".*lib" -E ".*scripts" -E ".*ci" -E ".*cmake"