sudo: require
language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode10.2 # Test macOS 10.14

    - os: osx
      osx_image: xcode10.1 # Test macOS 10.13
    
    - os: osx
      osx_image: xcode9.4 # Test macOS 10.13

    - os: osx
      osx_image: xcode8 # Test macOS 10.11

    - os: linux
      dist: trusty
      env: COMPILER_NAME=gcc CXX=g++-7 CC=gcc-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
            - cmake

    - os: linux
      dist: trusty
      env: COMPILER_NAME=gcc CXX=g++-6 CC=gcc-6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - cmake

    - os: linux
      dist: trusty
      env: COMPILER_NAME=clang CXX=clang++-6.0 CC=clang-6.0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
            - cmake

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  # Install GLFW dependency
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install xorg-dev libglu1-mesa-dev ; fi
  # Upgrade pip on macOS
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip install --upgrade pip --trusted-host pypi.org --trusted-host files.pythonhosted.org ; fi
  # Upgrade urllib3 on macOS
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip install --upgrade urllib3 ; fi
  # Install coveralls
  - pip install --user cpp-coveralls

script:
  - cmake -S ./Engine -B ./Engine/Build -DBUILD_EDITOR=OFF
  - cmake --build ./Engine/Build
  - ./Engine/Bin/SeedEngine-0.1.0Tests

after_success:
  - coveralls --root . -E ".*Extern." -E ".*Scripts" -E ".*CMake" -E ".*Build" -E ".*Test" -E ".*Config" -E ".*Resources" -E ".*Docs"