sudo: require
language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode10.2 # Test macOS 10.14

    - os: osx
      osx_image: xcode10.1 # Test macOS 10.13
    
    - os: osx
      osx_image: xcode9.2 # Test macOS 10.12

    - os: osx
      osx_image: xcode8 # Test macOS 10.11

    - os: osx
      osx_image: xcode6.4 # Test macOS 10.10

    - os: linux
      dist: trusty
      env: COMPILER_NAME=gcc CXX=g++-7 CC=gcc-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
            - cmake

    - os: linux
      dist: trusty
      env: COMPILER_NAME=gcc CXX=g++-6 CC=gcc-6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - cmake

    - os: linux
      dist: trusty
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
            - cmake

    - os: linux
      dist: trusty
      env: COMPILER_NAME=gcc CXX=g++-4.9 CC=gcc-4.9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
            - cmake

    - os: linux
      dist: trusty
      env: COMPILER_NAME=clang CXX=clang++-8.0 CC=clang-8.0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-8.0
          packages:
            - clang-8.0
            - cmake

    - os: linux
      dist: trusty
      env: COMPILER_NAME=clang CXX=clang++-7.0 CC=clang-7.0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7.0
          packages:
            - clang-7.0
            - cmake

    - os: linux
      dist: trusty
      env: COMPILER_NAME=clang CXX=clang++-6.0 CC=clang-6.0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
            - cmake

    - os: linux
      dist: trusty
      env: COMPILER_NAME=clang CXX=clang++-5.0 CC=clang-5.0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - cmake

    - os: linux
      dist: trusty
      env: COMPILER_NAME=clang CXX=clang++-4.0 CC=clang-4.0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - cmake

    - os: linux
      dist: trusty
      env: COMPILER_NAME=clang CXX=clang++-3.8 CC=clang-3.8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.8
          packages:
            - clang-3.8
            - cmake

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update                                      ; fi
  # Install GLFW dependency
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install xorg-dev libglu1-mesa-dev ; fi
  # Install coveralls
  - pip install --user cpp-coveralls
    #fi

script:
  - cmake . -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGRAPHICS_API:STRING=OPENGL
  - cmake --build .
  - ./bin/seed-engine-core-tests

after_success:
  - coveralls --root . -E ".*extern." -E ".*build" -E ".*bin" -E ".*lib" -E ".*scripts" -E ".*ci" -E ".*cmake"