version: '1.0.{build}'

image:
  - Visual Studio 2013
  - Visual Studio 2015
  - Visual Studio 2017

platform:
  - x64
  - Win32

configuration:
  - Release
  - Debug

install:
  - git submodule update --init --recursive

init:
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set GENERATOR="Visual Studio 15 2017" )
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set GENERATOR="Visual Studio 14 2015" )
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" ( set GENERATOR="Visual Studio 12 2013" )

before_build:
  - cmake -G %GENERATOR% -A %PLATFORM% -S . -B build\%CONFIGURATION%  -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGRAPHICS_API:STRING=OPENGL

build:
  project: $(APPVEYOR_BUILD_FOLDER)\build\$(CONFIGURATION)\$(APPVEYOR_PROJECT_NAME).sln

test_script:
  - '%APPVEYOR_BUILD_FOLDER%\bin\%CONFIGURATION%\seed-engine-core-tests.exe'