version: '1.0.{build}'

image: Visual Studio 2017

platform:
  - x64
  - x86

configuration:
  - Release
  - Debug

install:
  - git submodule update --init --recursive

before_build:
  - cmake -G "Visual Studio 15 2017 Win64" -S . -B '%APPVEYOR_BUILD_FOLDER%\%CONFIGURATION%  -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGRAPHICS_API:STRING=OPENGL

build:
  project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln

test_script:
  - '%APPVEYOR_BUILD_FOLDER%\%CONFIGURATION%\seed-engine-core-tests.exe'