name: Windows Build

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  VERSION_MAJOR: 0
  VERSION_MINOR: 1
  VERSION_PATCH: 0
  VERSION: 0.1.0
  ENGINE_FOLDER: ${{github.workspace}}/Engine
  BUILD_FOLDER: ${{github.workspace}}/Engine/Build
  BIN_FOLDER: ${{github.workspace}}/Engine/Bin

jobs:
  build:
    name: ${{matrix.config.name}}
    runs-on: ${{matrix.config.os}}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              name: "Windows Latest MSVC",
              os: windows-latest
            }

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Configure CMake
        run: cmake -S ${{env.ENGINE_FOLDER}} -B ${{env.BUILD_FOLDER}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_EDITOR=OFF -DBUILD_TESTS=ON

      - name: Build
        run: cmake --build ${{env.BUILD_FOLDER}} --config ${{env.BUILD_TYPE}} -j 16

      - name: Test
        working-directory: ${{env.BIN_FOLDER}}/${{env.BUILD_TYPE}}
        run: ./SeedEngine-${{env.VERSION}}Tests.exe

